// Generated by LiveScript 1.5.0
/**
 * @package Detox chat app
 * @author  Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @license 0BSD
 */
(function(){
  Polymer({
    is: 'detox-chat-app',
    properties: {
      chatId: {
        type: String,
        value: 'detox-chat-app'
      }
    }
  });
}).call(this);
