// Generated by LiveScript 1.5.0
/**
 * @package Detox chat app
 * @author  Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @license 0BSD
 */
(function(){
  function Wrapper(detoxChat, state){
    var state_instance, experience_level, help;
    state_instance = {
      properties: {
        chatId: {
          type: String,
          value: 'detox-chat-app'
        }
      },
      created: function(){
        this._state_instance = state.get_instance(this.chatId);
        if (!this._state_instance.ready()) {
          csw.functions.notify("Previous state was not found, new identity generated", 'warning', 'right', 60);
          this._state_instance.set_seed(detoxChat.generate_seed());
          this._state_instance.add_secret(detoxChat.generate_secret().slice(0, 4), 'Default secret');
        }
      }
    };
    experience_level = [
      state_instance, {
        advanced_user: {
          type: Boolean,
          value: false
        },
        developer: {
          type: Boolean,
          value: false
        },
        ready: function(){
          var state, this$ = this;
          state = this._state_instance;
          this.advanced_user = state.get_settings_experience() >= state.EXPERIENCE_ADVANCED;
          this.developer = state.get_settings_experience() === state.EXPERIENCE_DEVELOPER;
          state.on('settings_experience_changed', function(experience){
            this$.advanced_user = experience >= state.EXPERIENCE_ADVANCED;
            this$.developer = experience === state.EXPERIENCE_DEVELOPER;
          });
        }
      }
    ];
    help = [
      state_instance, {
        properties: {
          help: Boolean
        },
        ready: function(){
          var this$ = this;
          this.help = this._state_instance.get_settings_help();
          this._state_instance.on('settings_help_changed', function(help){
            this$.help = help;
          });
        }
      }
    ];
    return {
      state_instance: state_instance,
      experience_level: experience_level,
      help: help
    };
  }
  define(['@detox/chat', 'js/state'], Wrapper);
}).call(this);
