// Generated by LiveScript 1.5.0
/**
 * @package Detox chat app
 * @author  Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @license 0BSD
 */
(function(){
  var IN_APP, ref$;
  IN_APP = location.search === '?home';
  /**
   * Force passive listeners on in Polymer
   */
  Polymer.setPassiveTouchGestures(true);
  /**
   * Register service worker
   */
  if ('serviceWorker' in navigator && window.detox_sw_path) {
    require(['@detox/chat']).then(function(arg$){
      var detoxChat, this$ = this;
      detoxChat = arg$[0];
      detoxChat.ready(function(){
        navigator.serviceWorker.register(detox_sw_path).then(function(registration){
          registration.onupdatefound = function(){
            var installingWorker;
            installingWorker = registration.installing;
            installingWorker.onstatechange = function(){
              switch (installingWorker.state) {
              case 'installed':
                if (navigator.serviceWorker.controller) {
                  if (IN_APP) {
                    csw.functions.notify('Application was updated in background and new version ready to be used, restart to enjoy it', 'success', 'right', 10);
                  } else {
                    csw.functions.notify('Website was updated in background and new version ready to be used, refresh page to enjoy it', 'success', 'right', 10);
                  }
                } else {
                  if (IN_APP) {
                    csw.functions.notify('Application is ready to work offline', 'success', 'right', 10);
                  } else {
                    csw.functions.notify('Website is ready to work offline', 'success', 'right', 10);
                  }
                }
                break;
              case 'redundant':
                console.error('The installing service worker became redundant');
              }
            };
          };
        })['catch'](function(e){
          console.error('Error during service worker registration:', e);
        });
      });
    });
  }
  /**
   * Requesting persistent storage, so that data will not be lost unexpectedly under storage pressure
   */
  if (((ref$ = navigator.storage) != null ? ref$.persist : void 8) != null) {
    navigator.storage.persisted().then(function(persistent){
      if (!persistent) {
        console.info('Persistent storage is not yet granted, requesting...');
        navigator.storage.persist().then(function(granted){
          if (granted) {
            console.info('Persistent storage granted');
          } else {
            console.warn('Persistent storage denied, data may be lost under storage pressure');
          }
        });
      }
    });
  } else {
    console.warn('Persistent storage not supported, data may be lost under storage pressure');
  }
}).call(this);
