// Generated by LiveScript 1.5.0
/**
 * @package Detox chat app
 * @author  Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @license 0BSD
 */
(function(){
  Polymer({
    is: 'detox-chat-app-sidebar-profile',
    behaviors: [detoxChatApp.behaviors.state],
    properties: {
      id_base58: String,
      name: {
        observer: '_nickname_changed',
        type: String
      }
    },
    ready: function(){
      var this$ = this;
      Promise.all([require(['@detox/chat', '@detox/crypto']), this._state_instance_ready]).then(function(arg$){
        var ref$, detoxChat, detoxCrypto;
        ref$ = arg$[0], detoxChat = ref$[0], detoxCrypto = ref$[1];
        detoxCrypto.ready(function(){
          detoxChat.ready(function(){
            var state;
            state = this$._state_instance;
            this$.id_base58 = detoxChat.id_encode(detoxCrypto.create_keypair(state.get_seed()).ed25519['public'], new Uint8Array(0));
            this$.name = state.get_nickname();
            state.on('nickname_changed', function(new_name){
              if (this$.name !== new_name) {
                this$.name = new_name;
              }
            });
          });
        });
      });
    },
    _nickname_changed: function(){
      if (this.name !== this._state_instance.get_nickname()) {
        this._state_instance.set_nickname(this.name);
      }
    },
    _id_click: function(e){
      e.target.select();
    }
  });
}).call(this);
