// Generated by LiveScript 1.5.0
/**
 * @package Detox chat app
 * @author  Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @license 0BSD
 */
(function(){
  var x$, ref$;
  x$ = (ref$ = window.detoxChatApp || (window.detoxChatApp = {})).behaviors || (ref$.behaviors = {});
  x$.state = {
    properties: {
      chatId: {
        type: String,
        value: 'detox-chat-app'
      }
    },
    created: function(){
      var this$ = this;
      this._state_instance_ready = require(['@detox/chat', 'state']).then(function(arg$){
        var detoxChat, state;
        detoxChat = arg$[0], state = arg$[1];
        this$._state_instance = state.get_instance(this$.chatId);
        if (!this$._state_instance.ready()) {
          csw.functions.notify("Previous state was not found, new identity generated", 'warning', 'right');
          this$._state_instance.set_seed(detoxChat.generate_seed());
          this$._state_instance.add_secret(detoxChat.generate_secret().slice(0, 4), 'Default secret');
        }
      });
    }
  };
  x$.help = [
    detoxChatApp.behaviors.state, {
      properties: {
        help: Boolean
      },
      created: function(){
        var this$ = this;
        this._state_instance_ready.then(function(){
          this$.help = this$._state_instance.get_settings_help();
          this$._state_instance.on('settings_help_changed', function(help){
            this$.help = help;
          });
        });
      }
    }
  ];
}).call(this);
