// Generated by LiveScript 1.5.0
/**
 * @package Detox chat app
 * @author  Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @license 0BSD
 */
(function(){
  Polymer({
    is: 'detox-chat-app-sidebar-settings',
    behaviors: [detoxChatApp.behaviors.state],
    properties: {
      settings_announce: {
        observer: '_settings_announce_changed',
        type: String
      }
    },
    ready: function(){
      var this$ = this;
      this._state_instance_ready.then(function(){
        var state;
        state = this$._state_instance;
        this$.settings_announce = this$._bool_to_string(state.get_settings_announce());
        state.on('settings_announce_changed', function(new_settings_announce){
          new_settings_announce = this$._bool_to_string(new_settings_announce);
          if (this$.settings_announce !== new_settings_announce) {
            this$.settings_announce = new_settings_announce;
          }
        });
      });
    },
    _bool_to_string: function(value){
      if (value) {
        return '1';
      } else {
        return '0';
      }
    },
    _settings_announce_changed: function(){
      if (this.settings_announce !== this._bool_to_string(this._state_instance.get_settings_announce())) {
        this._state_instance.set_settings_announce(this.settings_announce === '1');
      }
    },
    _help_settings_announce: function(){
      var content;
      content = "<p>It is possible to use Detox Chat without announcing itself to the network.<br>\nIn this case incoming connections from contacts will not be possible, but it will be possible to initiate connection to other contacts if needed.</p>";
      csw.functions.simple_modal(content);
    }
  });
}).call(this);
