// Generated by LiveScript 1.5.0
/**
 * @package Detox chat app
 * @author  Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @license 0BSD
 */
(function(){
  Polymer({
    is: 'detox-chat-app-sidebar-status',
    behaviors: [detoxChatApp.behaviors.state],
    properties: {
      network_connected: {
        type: Boolean,
        value: false
      },
      network_state: {
        computed: '_network_state(network_connected)',
        type: String
      },
      announced: {
        type: Boolean,
        value: false
      },
      announced_string: {
        computed: '_announced_string(announced)',
        type: String
      }
    },
    ready: function(){
      var this$ = this;
      Promise.all([require(['state']), this._state_instance_ready]).then(function(arg$){
        var detoxState, state;
        detoxState = arg$[0][0];
        state = this$._state_instance;
        state.on('online_updated', function(){
          this$.network_connected = state.get_online();
        }).on('announced_updated', function(){
          this$.announced = state.get_announced();
        });
      });
    },
    _network_state: function(network_connected){
      if (network_connected) {
        return 'Online';
      } else {
        return 'Offline';
      }
    },
    _announced_string: function(announced){
      if (announced) {
        return 'Yes';
      } else {
        return 'No';
      }
    }
  });
}).call(this);
